---
title: "bpip: Rotated building"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
  toc: true
keep_md: true
vignette: >
  %\VignetteIndexEntry{bpip: Rotated building}
  %\VignetteEngine{knitr::rmarkdown}
---
  
## Running BPIP for a rotated building
  
This example creates downwash inputs for a 10x10x10 building that is rotated 45 degrees and located 20 meters West of the air emissions source.

## Install BPIP to a new EPA folder in working directory
```{r eval = T}
library(installEPA)

install_epa("bpip", dir = "EPA")
```

## Create new bpip table
```{r }
library(bpip)
builds <- new_bpip()

library(knitr)
kable(builds)
```

## Adjust building parameters
```{r }
builds$bld_rotation      <- 45

builds$length_x          <- 10

builds$angle_from_source <- 270 

kable(builds)
```

## Plot building
```{r }
plot_bpip(builds)
```


## Add a building
```{r }
builds <- rbind(builds, builds)

builds$building[2]          <- "Bld_2"

builds$angle_from_source[2] <- 90

builds$bld_rotation[2]      <- 60

builds$bld_height[2]        <- 15

kable(builds)
```

## Plot buildings
```{r }
plot_bpip(builds)
```

## Create bpip input file
```{r }
write_bpip(builds, "rotated_building.bpi")
```

## Run bpip
```{r }
run_bpip("rotated_building.bpi", "rotated_results", exe_folder = "EPA/")
```

## Read results
```{r }
results <- read_bpip_out(file = "rotated_results.out", as_text = FALSE)

kable(results)
```
